---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: default
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: mediawiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: default
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: apache
        image: "shakilife/mediawiki:latest"
        ports:
        - containerPort: 80
          #        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mediawiki-secret
        resources:
          limits:
            memory: "500Mi"
            cpu: "250m"
      - name: mysql
        image: "mysql:5.5"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mediawiki-secret        
      volumes:
      - name: data
        hostPath:
          path: data      
      restartPolicy: Always  

